\hypertarget{Makefile}{\section{Referência do Arquivo /home/lpgoulart/\-Morse\-Translator/\-Makefile}
\label{Makefile}\index{/home/lpgoulart/\-Morse\-Translator/\-Makefile@{/home/lpgoulart/\-Morse\-Translator/\-Makefile}}
}
